# Generated by Django 4.1.4 on 2023-06-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
    ]
